// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://leyeltbhwuxssawmhqcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxleWVsdGJod3V4c3Nhd21ocWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MjYxNDMsImV4cCI6MjA2NDIwMjE0M30.CUtVvWXt10-L_Bsx8oUHp541sLZr9DPIabU6Uy8XAkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});